services:
  manager:
    build: ./manager
    ports:
      - "8080:8080"
    environment:
      - WORKER_URLS=http://worker1:8081,http://worker2:8082,http://worker3:8083
    networks:
      - crackhash_net

  worker1:
    build: ./worker
    environment:
      - MANAGER_URL=http://manager:8080
      - PORT=8081
    networks:
      - crackhash_net

  worker2:
    build: ./worker
    environment:
      - MANAGER_URL=http://manager:8080
      - PORT=8082
    networks:
      - crackhash_net

  worker3:
    build: ./worker
    environment:
      - MANAGER_URL=http://manager:8080
      - PORT=8083
    networks:
      - crackhash_net

networks:
  crackhash_net:
      driver: bridge